### ISSUE TITLE
TYPO3 10 LTS compatible version?

### ISSUE THREAD

**Issue by wini2** [jweiland-net/kk_downloader#6]
Hello,

are ther any plans to release a kk_downloader version which is compatible with TYPO3 10 in the near future?

best regards

**Comment by froemken** [comment]
@wini2 

I'm just working on it: https://github.com/jweiland-net/kk_downloader/pull/7
But it will not be fully compatible with previous TYPO3 versions. Of cause we keep DB structure, but everything else will be Extbase/Fluid.

Stefan

**Comment by froemken** [comment]
Hello @wini2 

kk_downloader is TYPO3 10 compatible since version 6.0.0. I have just released version 6.1.0 today.

Have a cool start into upcoming weekend

Stefan
